version: '3'

services:
  plex:
    image: linuxserver/plex
    container_name: Plex
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= YOUR_CLAIM_TOKEN
    ports:
      - 32400:32400
    volumes:
      - /path/to/library/medias:/data
      - /path/to/library/plex:/config

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - 7878:7878
    volumes:
      - /path/to/library/radarr:/config
      - /path/to/library/medias/films:/movies
      - /path/to/library/downloads:/downloads

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    volumes:
      - /path/to/library/sonarr:/config
      - /path/to/library/medias/series:/tv
      - /path/to/library/downloads:/downloads

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /path/to/library/qbittorrent:/config
      - /path/to/library/downloads:/downloads

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - 9117:9117
    volumes:
      - /path/to/library/jackett:/config
      - /path/to/library/downloads:/downloads

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    restart: always
    ports:
      - 8191:8191

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    restart: always
    ports:
      - 5055:5055
    volumes:
      - /path/to/library/overseerr:/config
